version: 2
project_name: ping_exporter
dist: dist
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_arm
      - linux_arm64
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    main: .
    ldflags: -s -w -X github.com/prometheus/common/version.Version={{.Version}} -X github.com/prometheus/common/version.Revision={{.Commit}} -X github.com/prometheus/common/version.BuildDate={{.Date}}
    binary: ping_exporter
archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}.
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.md
      - LICENSE*
    wrap_in_directory: false
snapshot:
  version_template: SNAPSHOT-{{ .Commit }}
nfpms:
  - vendor: zebbra AG
    homepage: "https://github.com/zebbra/ping_exporter"
    maintainer: zebbra AG
    description: "Prometheus Ping Exporter"
    license: Apache 2.0 License
    formats:
      - deb
      - rpm
    bindir: /usr/bin
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
