apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ping_exporter.fullname" . }}
  labels:
    {{- include "ping_exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ping_exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ping_exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ping_exporter.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --log.level={{ .Values.pingExporter.args.logLevel }}
            - --log.format={{ .Values.pingExporter.args.logFormat }}
            - --web.listen-address={{ .Values.pingExporter.args.webListenAddress }}
            - --ping.default-count={{ .Values.pingExporter.args.defaultCount }}
            - --ping.default-interval={{ .Values.pingExporter.args.defaultInterval }}
            - --ping.default-packet-size={{ .Values.pingExporter.args.defaultPacketSize }}
            - --ping.default-timeout={{ .Values.pingExporter.args.defaultTimeout }}
            - --ping.max-count={{ .Values.pingExporter.args.maxCount }}
            - --ping.max-packet-size={{ .Values.pingExporter.args.maxPacketSize }}
            {{- if .Values.pingExporter.webConfig.enabled }}
            - --web.config.file=/etc/ping_exporter/web.yml
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.pingExporter.webConfig.enabled }}
            - name: web-config
              mountPath: /etc/ping_exporter
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.pingExporter.webConfig.enabled }}
        - name: web-config
          secret:
            secretName: {{ include "ping_exporter.fullname" . }}-web-config
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
