{{- if .Values.pingExporter.webConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ping_exporter.fullname" . }}-web-config
  labels:
    {{- include "ping_exporter.labels" . | nindent 4 }}
type: Opaque
data:
  web.yml: {{ .Values.pingExporter.webConfig.config | toYaml | b64enc }}
{{- end }}